Student.create!([
  {first_name: "Luke", last_name: "O'Connor", email: "luke@luke.com", password: "password", phone_number: "1-503-078-9934", short_bio: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering.", linkedin_url: "linkedin.com/nicolas", twitter_handle: "twitter.com/try-hard", website_url: "harris.name", online_resume_url: "bechtelar.info", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/remomnisipsum.png?size=300x300&set=set1"},
  {first_name: "Annie", last_name: "Wong", email: "annie@annie.com", password: "password", phone_number: "1-246-722-9332", short_bio: "Truly wonderful, the mind of a child is.", linkedin_url: "linkedin.com/mosciski", twitter_handle: "twitter.com/franzen", website_url: "pouros.org", online_resume_url: "cronahyatt.com", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/nullaenimillo.png?size=300x300&set=set1"},
  {first_name: "Jenilee", last_name: "Hsu", email: "jenilee@jenilee.com", password: "password", phone_number: "1-370-137-2715", short_bio: "You know, that little droid is going to cause me a lot of trouble.", linkedin_url: "linkedin.com/keelingklocko", twitter_handle: "twitter.com/post-ironic", website_url: "schulistschumm.com", online_resume_url: "pfeffer.info", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/euminerror.png?size=300x300&set=set1"},
  {first_name: "Noelle", last_name: "Salta", email: "noelle@noelle.com", password: "password", phone_number: "610.489.6139", short_bio: "A Jedi uses the Force for knowledge and defense, never for attack.", linkedin_url: "linkedin.com/macgyver", twitter_handle: "twitter.com/paleo", website_url: "konopelski.net", online_resume_url: "satterfield.info", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/blanditiissuscipitexercitationem.png?size=300x300&set=set1"},
  {first_name: "George", last_name: "Mikhail", email: "george@george.com", password: "password", phone_number: "(649) 153-0019", short_bio: "If you're saying that coming here was a bad idea, I'm starting to agree with you.", linkedin_url: "linkedin.com/blick", twitter_handle: "twitter.com/tattooed", website_url: "bechtelar.net", online_resume_url: "hoppe.net", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/quisetrerum.png?size=300x300&set=set1"},
  {first_name: "Dani", last_name: "Zaghian", email: "dani@dani.com", password: "password", phone_number: "271-034-9839", short_bio: "You do have your moments. Not many, but you have them.", linkedin_url: "linkedin.com/trantow", twitter_handle: "twitter.com/helvetica", website_url: "metzborer.org", online_resume_url: "hodkiewiczdare.name", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/beataeconsequaturquia.png?size=300x300&set=set1"},
  {first_name: "Matt", last_name: "Gainer", email: "matt@matt.com", password: "password", phone_number: "1-997-659-6442", short_bio: "A Jedi uses the Force for knowledge and defense, never for attack.", linkedin_url: "linkedin.com/olson", twitter_handle: "twitter.com/ethical", website_url: "wintheiser.net", online_resume_url: "carroll.info", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/dolorbeataequis.png?size=300x300&set=set1"},
  {first_name: "Sagar", last_name: "Miglani", email: "sagar@sagar.com", password: "password", phone_number: "(796) 832-8287", short_bio: "Bounty hunters! We don't need this scum.", linkedin_url: "linkedin.com/johnston", twitter_handle: "twitter.com/artisan", website_url: "jaskolski.co", online_resume_url: "larkin.co", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/hicsintminus.png?size=300x300&set=set1"},
  {first_name: "Lizzy", last_name: "Mikhailovskaia", email: "lizzy@lizzy.com", password: "password", phone_number: "1-464-813-4829", short_bio: "Well, you said you wanted to be around when I made a mistake.", linkedin_url: "linkedin.com/kreiger", twitter_handle: "twitter.com/literally", website_url: "barrows.info", online_resume_url: "crona.name", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/voluptatemearerum.png?size=300x300&set=set1"},
  {first_name: "Jim", last_name: "Tekanyo", email: "jim@jim.com", password: "password", phone_number: "932.482.5289", short_bio: "Do. Or do not. There is no try.", linkedin_url: "linkedin.com/metz", twitter_handle: "twitter.com/hoodie", website_url: "oharawilliamson.net", online_resume_url: "baileywuckert.org", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/eligendiveloptio.png?size=300x300&set=set1"},
  {first_name: "Wen", last_name: "Zhang", email: "iwenyou@wen.com", password: "password", phone_number: "700-024-9974", short_bio: "You are unwise to lower your defenses!", linkedin_url: "linkedin.com/kilback", twitter_handle: "twitter.com/chambray", website_url: "swaniawskiheathcote.io", online_resume_url: "miller.co", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/nobisdistinctiosunt.png?size=300x300&set=set1"},
  {first_name: "Jens", last_name: "Nordgaard", email: "jens@jens.com", password: "password", phone_number: "1-396-120-3886", short_bio: "You know, that little droid is going to cause me a lot of trouble.", linkedin_url: "linkedin.com/hagenesschowalter", twitter_handle: "twitter.com/cray", website_url: "reichelgreenholt.org", online_resume_url: "vonrueden.io", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/necessitatibusfugitvoluptatibus.png?size=300x300&set=set1"},
  {first_name: "Carlos", last_name: "Parilla", email: "carlos@carlos.com", password: "password", phone_number: "115-335-5484", short_bio: "Do. Or do not. There is no try.", linkedin_url: "linkedin.com/swaniawski", twitter_handle: "twitter.com/cornhole", website_url: "hills.co", online_resume_url: "farrellkautzer.org", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/consequaturestvero.png?size=300x300&set=set1"},
  {first_name: "Andrew ", last_name: "Taylor", email: "andrew@andrew.com", password: "password", phone_number: "1-945-971-7686", short_bio: "You know, that little droid is going to cause me a lot of trouble.", linkedin_url: "linkedin.com/schinner", twitter_handle: "twitter.com/master", website_url: "fadelhettinger.name", online_resume_url: "schmeler.io", github_url: "github.com/danimalkingdom", photo: "https://robohash.org/istequisquameos.png?size=300x300&set=set1"}
])